apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-task
spec:
  workspaces:
    - name: source
      mountPath: /workspace
  steps:
    - name: deploy
      image: bitnami/kubectl:latest
      workingDir: /workspace
      script: |
        #!/bin/sh
        set -e
        kubectl apply -f k8s/services/
        kubectl apply -f k8s/networking/
        kubectl apply -f k8s/deployments/postgres-statefulset.yaml
        kubectl apply -f k8s/deployments/backend-deployment.yaml
        kubectl apply -f k8s/deployments/frontend-deployment.yaml
