apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push-task
spec:
  params:
    - name: IMAGE
      description: "Nombre completo de la imagen (incluye registry y tag)"
      type: string
      default: "docker.io/aramos20/myapi:latest"
    - name: CONTEXT_DIR # ⚠️ Error 1: Ruta incorrecta
      description: "Directorio donde se encuentra el Dockerfile, relativo al workspace"
      type: string
      default: "app" # ✔️ Corrección: Usa "app" en lugar de "source/aramos20-test/app"
  workspaces:
    - name: source
      mountPath: /workspace/source
  steps:
    - name: debug
      image: alpine:latest
      script: |
        echo "=== Estructura del Workspace ==="
        ls -la $(workspaces.source.path)
        echo "=== Contenido de app/ ==="
        ls -la $(workspaces.source.path)/app
        echo "=== Dockerfile Existe? ==="
        cat $(workspaces.source.path)/app/Dockerfile

    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      workingDir: $(workspaces.source.path)/$(params.CONTEXT_DIR)
      command:
        - /kaniko/executor
      args:
        - --dockerfile=Dockerfile
        - --context=.
        - --destination=$(params.IMAGE)
        - --insecure
        - --skip-tls-verify
      volumeMounts: # ✔️ Monta el Secret como volumen
        - name: dockerhub-config
          mountPath: /kaniko/.docker
  volumes: # ✔️ Referencia el Secret
    - name: dockerhub-config
      secret:
        secretName: dockerhub-credentials
        items:
          - key: .dockerconfigjson
            path: config.json
