apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push-task
spec:
  params:
    - name: IMAGE
      description: "Nombre completo de la imagen"
      type: string
      default: "docker.io/aramos20/myapi:latest"
    - name: CONTEXT_DIR
      description: "Directorio del Dockerfile (relativo al workspace)"
      type: string
      default: "app"
  workspaces:
    - name: source
      mountPath: /workspace/source
    - name: artifacts
      mountPath: /artifacts
  steps:
    - name: kaniko-build
      image: gcr.io/kaniko-project/executor:debug
      workingDir: /workspace/source # Cambia al directorio raíz del workspace
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(params.CONTEXT_DIR)/Dockerfile # Ruta completa al Dockerfile
        - --context=/workspace/source # Contexto es el workspace completo
        - --no-push
        - --destination=$(params.IMAGE)
        - --tar-path=/artifacts/image.tar

    # Step 2: Push con Crane
    - name: crane-push
      image: gcr.io/go-containerregistry/crane:debug
      script: |
        # Autenticación en Docker Hub usando variables de entorno
        crane auth login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" docker.io

        # Push del archivo .tar
        crane push /artifacts/image.tar $(params.IMAGE)
      env:
        - name: DOCKER_USERNAME
          valueFrom:
            secretKeyRef:
              name: dockerhub-credentials
              key: username # Asegúrate de que el Secret tenga esta clave
        - name: DOCKER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dockerhub-credentials
              key: password # Asegúrate de que el Secret tenga esta clave
