apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push-task
spec:
  params:
    - name: IMAGE
      description: "Nombre completo de la imagen"
      type: string
      default: "docker.io/aramos20/myapi:latest"
    - name: CONTEXT_DIR
      description: "Directorio del Dockerfile (relativo al workspace)"
      type: string
      default: "app"
  workspaces:
    - name: source
      mountPath: /workspace/source
    - name: artifacts
      mountPath: /workspace/artifacts # ¡CORREGIDO!
  steps:
    - name: kaniko-build
      image: gcr.io/kaniko-project/executor:debug
      workingDir: /workspace/source
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(params.CONTEXT_DIR)/Dockerfile
        - --context=/workspace/source
        - --no-push
        - --destination=$(params.IMAGE)
        - --tar-path=/workspace/artifacts/image.tar

    - name: crane-push
      image: gcr.io/go-containerregistry/crane:debug
      command: ["/bin/sh", "-c"]
      args:
        - |
          crane auth login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" docker.io
          crane push /workspace/artifacts/image.tar $(params.IMAGE) # Ajusta la ruta aquí también
      env:
        - name: DOCKER_USERNAME
          valueFrom:
            secretKeyRef:
              name: dockerhub-credentials
              key: username
        - name: DOCKER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dockerhub-credentials
              key: password
      volumeMounts:
        - name: artifacts
          mountPath: /workspace/artifacts
