apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-task
spec:
  params:
    - name: MANIFEST_DIR
      description: "Directorio con los manifiestos de Kubernetes (relativo al workspace)"
      type: string
      default: "k8s"
  workspaces:
    - name: source # Nombre del workspace
      mountPath: /workspace/source # Path dentro del contenedor
  steps:
    - name: deploy
      image: bitnami/kubectl:latest
      workingDir: /workspace/source # Importante: workingDir dentro del workspace
      script: |
        #!/bin/sh
        set -ex
        kubectl apply -f $(params.MANIFEST_DIR)/backend.yaml
        kubectl apply -f $(params.MANIFEST_DIR)/configmap.yaml
        kubectl apply -f $(params.MANIFEST_DIR)/frontend.yaml
        kubectl apply -f $(params.MANIFEST_DIR)/postgres.yaml
        kubectl apply -f $(params.MANIFEST_DIR)/secrets.yaml
