apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone-task
spec:
  params:
    - name: url
      type: string
      description: "URL del repositorio Git"
      default: "https://github.com/aramos20/test.git"
    - name: revision
      type: string
      description: "Branch o commit a clonar"
      default: "main"
  workspaces:
    - name: output
      mountPath: /workspace/source
  steps:
    - name: clone
      image: alpine/git:latest
      script: |
        #!/bin/sh
        set -ex
        rm -rf $(workspaces.output.path)/*
        git clone $(params.url) $(workspaces.output.path)/.  # Clona en la raíz del workspace
        cd $(workspaces.output.path)
        git checkout $(params.revision)
