apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-deploy-pipeline-run-xlznq
  namespace: tekton-pipelines
spec:
  pipelineRef:
    name: build-deploy-pipeline
  workspaces:
    - name: source-code
      persistentVolumeClaim:
        claimName: tekton-pvc
  params:
    - name: imageName
      value: testapi:latest
  serviceAccountName: tekton-webhook
kubectl describe pipelinerun build-deploy-pipeline-run-xlznq -n tekton-pipelines