apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ci-cd-pipeline-run
spec:
  serviceAccountName: tekton-service-account
  pipelineRef:
    name: ci-cd-pipeline
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: tekton-pvc
  params:
    - name: IMAGE
      value: "docker.io/aramos20/myapi:latest"
