apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ci-cd-pipeline-run
spec:
  pipelineRef:
    name: ci-cd-pipeline
  workspaces:
    - name: source-workspace
      persistentVolumeClaim:
        claimName: tekton-pvc
    - name: artifacts-workspace
      persistentVolumeClaim:
        claimName: tekton-pvc # O un PVC diferente si lo prefieres
  params:
    - name: IMAGE
      value: "docker.io/aramos20/myapi:latest"
  serviceAccountName: tekton-service-account # Añade el service account
