apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ci-cd-pipeline-run
spec:
  pipelineRef:
    name: ci-cd-pipeline
  workspaces:
    - name: shared-workspace # Este es el Workspace que requiere el Pipeline
      persistentVolumeClaim:
        claimName: tekton-pvc # Usa el PVC que ya tienes configurado
    - name: artifacts-workspace
      persistentVolumeClaim:
        claimName: tekton-pvc-artifacts # El PVC para los artifacts de Kaniko
  params:
    - name: IMAGE
      value: "docker.io/aramos20/myapi:latest"
  serviceAccountName: tekton-service-account
