apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-cd-pipeline
spec:
  params:
    - name: IMAGE
      type: string
      default: "docker.io/aramos20/myapi:latest"
  workspaces:
    - name: source
    - name: artifacts
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone-task
      workspaces:
        - name: output
          workspace: source

    - name: build-and-push
      runAfter:
        - clone-repo
      taskRef:
        name: build-and-push-task
      workspaces:
        - name: source
          workspace: source
        - name: artifacts
          workspace: artifacts
      params:
        - name: IMAGE
          value: "$(params.IMAGE)"

    - name: deploy
      runAfter: # Ejecutar después de build-and-push
        - build-and-push
      taskRef:
        name: deploy-task
      workspaces:
        - name: source
          workspace: source # El deploy task necesita acceso al repo clonado
