apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-deploy
spec:
  workspaces:
    - name: source
  params:
    - name: image
      type: string

  steps: 
    - name: build
      image: gcr.io/kaniko-project/executor:v1.5.1
      securityContext:
        runAsUSer: 0
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(workspaces.source.path)/app/Dockerfile
        - --context=$(workspaces.source.path)/app
        - --destination=$(params.image)
        - --digest-file=$(results.IMAGE_DIGEST.path)
        - --insecure
        - --skip-tls-verify
      securityContext:
        runAsUser: 0

    - name: deploy
      image: bitnami/kubectl:latest
      command:
        - kubectl
      args:
        - apply
        - -f
        - $(workspaces.source.path)/k8s
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-deploy-pipeline
spec:
  workspaces:
    - name: source-code
  params:
    - name: imageName
      type: string
  tasks:
    - name: build-and-deploy
      taskRef:
        name: build-deploy
      workspaces:
        - name: source
          workspace: source-code
      params:
        - name: image
          value: $(params.imageName)
