apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-pvc-artifacts
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-service-account
secrets:
  - name: dockerhub-credentials
imagePullSecrets:
  - name: dockerhub-credentials

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-run-access
  namespace: default
subjects:
  - kind: ServiceAccount
    name: tekton-service-account
    namespace: default
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io
