---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-files
data:
  index.html: |
    <html>
      <head>
        <title>My Frontend</title>
      </head>
      <body>
        <h1>Welcome to my frontend</h1>
        <script>
          fetch('http://127.0.0.1:30007/visits')
            .then(response => response.json())
            .then(data => {
              document.body.innerHTML += `<p>${data.message} - Visitas: ${data.visits} - Modo: ${data.mode}</p>`;
            })
            .catch(error => {
              console.error('Error fetching data:', error);
            });
        </script>
      </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: nginx:alpine
          resources:
            limits:
              cpu: "2" #
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "1Gi"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: static-files
              mountPath: /usr/share/nginx/html
      volumes:
        - name: static-files
          configMap:
            name: frontend-files
            items:
              - key: index.html
                path: index.html
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
      nodePort: 30010
  type: NodePort
