apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-cd-pipeline
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone-task
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: build-and-push
      runAfter: [clone-repo]
      taskRef:
        name: build-and-push-task
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: start-tunnel
      runAfter: [build-and-push]
      taskRef:
        name: tunnel-task

    - name: deploy
      runAfter: [start-tunnel]
      taskRef:
        name: deploy-task
      workspaces:
        - name: source
          workspace: shared-workspace
