apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - name: backend
      port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 30007
  type: ClusterIP
